config/routes.rb
Rails.application.routes.draw do
  resources :meal_preps
  root "home#index"
  
  resources :recipes do 
    resources :recipe_steps
    resources :recipe_ingredients
  end
  resources :locations
  get 'users/index'
  resources :ingredients
  resources :states
  resources :units
  #devise_for :users
  devise_for :users, controllers: { registrations: "registrations" }
  #get 'home/index'
  #get 'create_update/index'
  get "home/about"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
  get "recipe_ingredients/test"
end

app/models/recipe_step.rb
class RecipeStep < ApplicationRecord
    belongs_to :recipe
    belongs_to :user
end

app/controllers/recipe_steps_controller.rb
class RecipeStepsController < ApplicationController
  before_action :get_recipe
  #before_action :set_recipe_step, only: %i[ show edit update destroy ]
  before_action :set_recipe_step, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  #Only allow editing, updating and destroying of states associated with the current user
  before_action :correct_user, only: [:edit, :update, :destroy]
  # GET /recipe_steps or /recipe_steps.json
  def index
    #See note under index for recipe_ingredients - this change fundamentally changes how admins interact with recipe steps. It might not be a big deal
    @recipe_steps = @recipe.recipe_steps.order(step_number: :asc)
  end

  # GET /recipe_steps/1 or /recipe_steps/1.json
  def show
  end

  # GET /recipe_steps/new
  def new
    @recipe_step = @recipe.recipe_steps.build
  end

  # GET /recipe_steps/1/edit
  def edit
  end

  # POST /recipe_steps or /recipe_steps.json
  def create
    @recipe_step = @recipe.recipe_steps.build(recipe_step_params)

    respond_to do |format|
      if @recipe_step.save
        format.turbo_stream do
          render turbo_stream: turbo_stream.append("recipe-steps-container", partial: "recipe_steps/recipe_step", locals: {recipe: @recipe, recipe_step: @recipe_step})
        end
        format.html { redirect_to recipe_path(@recipe), notice: "Recipe step was successfully created." }
        format.json { render :show, status: :created, location: @recipe_step }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipe_step.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipe_steps/1 or /recipe_steps/1.json
  def update
    respond_to do |format|
      if @recipe_step.update(recipe_step_params)
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace(@recipe_step, partial: "recipe_steps/recipe_step", locals: {recipe: @recipe, recipe_step: @recipe_step})
        end
        format.html { redirect_to recipe_path(@recipe), notice: "Recipe step was successfully updated." }
        format.json { render :show, status: :ok, location: @recipe_step }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @recipe_step.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipe_steps/1 or /recipe_steps/1.json
  def destroy
    @recipe_step.destroy

    respond_to do |format|
      format.html { redirect_to recipe_path(@recipe), notice: "Recipe step was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def correct_user
      @recipe_step = current_user.recipe_steps.find_by(id: params[:id])
      redirect_to recipe_steps_path, notice: "Not authorized!" if @recipe_step.nil?
    end
    def get_recipe
      @recipe = Recipe.find(params[:recipe_id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_recipe_step
      @recipe_step = RecipeStep.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def recipe_step_params
      params.require(:recipe_step).permit(:recipe_id, :step_number, :step_text, :user_id)
    end
end

app/helpers/recipe_steps_helper.rb
module RecipeStepsHelper
end

app/views/recipe_steps/_form.html.erb
<%= form_with(model: [@recipe, recipe_step]) do |form| %>
  <% if recipe_step.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(recipe_step.errors.count, "error") %> prohibited this recipe_step from being saved:</h2>

      <ul>
        <% recipe_step.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="modal-body">
    <div>
      <%= form.label :step_number, style: "display: block" %>
      <%= form.number_field :step_number %>
    </div>

    <div>
      <%= form.label :step_text, style: "display: block" %>
      <%= form.text_area :step_text, class:"textAreaChanger" %>
    </div>
    <div>
      <%= form.number_field :user_id, id: :recipe_step_user_id, value: current_user.id, type: :hidden %>
    </div>
  </div>
  <div class="modal-footer">
    <%= form.submit class: "btn btn-secondary" %>
  </div>
<% end %>

app/views/recipe_steps/_recipe_step.html.erb
<li id="<%= dom_id recipe_step %>">
  <%= recipe_step.step_number.to_s + ". " + recipe_step.step_text %>
  <div>
    <%= link_to edit_recipe_recipe_step_path(@recipe, recipe_step), data:{turbo_frame: "zFormModal", controller: "z-form-modal", action: "z-form-modal#showModal"} do %>
      <i class="bi bi-pencil"></i>
    <% end %>
    <%= link_to [@recipe, recipe_step], data: {turbo_method: :delete, turbo_confirm: "Delete step from recipe?"} do %>
      <i class="bi bi-trash3"></i>
    <% end %>
    </div>
</li>

app/views/recipe_steps/edit.html.erb
<%= turbo_frame_tag :zFormModal do %>
  <div data-controller="z-form-modal" data-action="turbo:submit-end->z-form-modal#submitEnd">
    <div class="modal-header themeColor">
      <h5 class="modal-title" id="staticBackdropLabel">Editing recipe step</h5>
      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
    </div>
    <%= render "form", recipe_step: @recipe_step %>
  </div>
<% end %>

app/views/recipe_steps/index.html.erb
<p style="color: green"><%= notice %></p>

<h1><%= @recipe.name %> recipe steps</h1>

<div id="recipe_steps">
  <% @recipe_steps.order(step_number: :asc).each do |recipe_step| %>
    <div><%= recipe_step.step_number.to_s + ". " + recipe_step.step_text %></div>
    <div><%= link_to "Edit", edit_recipe_recipe_step_path(@recipe, recipe_step),class:"btn btn-secondary" %></div>
    <div><%= link_to "Delete", [@recipe, recipe_step], data: {turbo_method: :delete, turbo_confirm: "Delete step?"},class:"btn btn-secondary" %></div>
  <% end %>
  <%= link_to "Back to Recipe", recipe_path(@recipe) %>
</div>

app/views/recipe_steps/new.html.erb
<%= turbo_frame_tag :zFormModal do %>
  <div data-controller="z-form-modal" data-action="turbo:submit-end->z-form-modal#submitEnd">
    <div class="modal-header themeColor">
      <h5 class="modal-title" id="staticBackdropLabel">New recipe step for <%= @recipe_step.recipe.name %></h5>
      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
    </div>
    <%= render "form", recipe_step: @recipe_step %>
  </div>
<% end %>

app/views/recipe_steps/show.html.erb
<p style="color: green"><%= notice %></p>
<%#= link_to "New recipe step", new_recipe_step_path %>
<%= render @recipe_step %>

<!--<div>
  <%#= link_to "Edit this recipe step", edit_recipe_step_path(@recipe_step) %> |
  <%#= link_to "Back to recipe steps", recipe_steps_path %>

  <%#= button_to "Destroy this recipe step", @recipe_step, method: :delete %>
</div>-->