config/routes.rb
Rails.application.routes.draw do
  resources :meal_preps
  root "home#index"
  
  resources :recipes do 
    resources :recipe_steps
    resources :recipe_ingredients
  end
  resources :locations
  get 'users/index'
  resources :ingredients
  resources :states
  resources :units
  #devise_for :users
  devise_for :users, controllers: { registrations: "registrations" }
  #get 'home/index'
  #get 'create_update/index'
  get "home/about"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
  get "recipe_ingredients/test"
end

app/models/recipe.rb
class Recipe < ApplicationRecord
    belongs_to :user
    has_many :recipe_steps, dependent: :destroy
    has_many :recipe_ingredients, dependent: :destroy
    has_many :ingredients, :through => :recipe_ingredients
    has_many :units, :through => :recipe_ingredients
    has_many :meal_preps

    validates :name, presence: true
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  #before_action :set_recipe, only: %i[ show edit update destroy ]
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  #Only allow editing, updating and destroying of states associated with the current user
  before_action :correct_user, only: [:edit, :update, :destroy]
  # GET /recipes or /recipes.json
  def index
    if current_user.admin == "T"
      @recipes = Recipe.all.order(name: :asc)
    else
      @recipes = current_user.recipes.order(name: :asc)
    end
  end

  # GET /recipes/1 or /recipes/1.json
  def show
    @recipe_ingredients = @recipe.recipe_ingredients.includes(:ingredient).order("ingredients.name ASC")
    @recipe_steps = @recipe.recipe_steps.order("recipe_steps.step_number")
  end

  # GET /recipes/new
  def new
    #@recipe = Recipe.new
    #@state = current_user.states.build
    @recipe = current_user.recipes.build
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes or /recipes.json
  def create
    #@recipe = Recipe.new(recipe_params)
    @recipe = current_user.recipes.build(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.turbo_stream do
          render turbo_stream: turbo_stream.prepend("recipes", partial: "recipes/recipe", locals: {recipe: @recipe})
        end

        format.html { redirect_to recipe_url(@recipe), notice: "Recipe was successfully created." }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1 or /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace("recipeTitle", partial: "recipes/recipeTitle", locals: {recipe: @recipe})
        end
        format.html { redirect_to recipe_url(@recipe), notice: "Recipe was successfully updated." }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1 or /recipes/1.json
  def destroy
    @recipe.destroy

    respond_to do |format|
      #format.html { redirect_to recipes_url, notice: "Recipe was successfully destroyed." }
      format.html { redirect_to recipes_path, status: :see_other, notice: "Recipe was successfully destroyed." }
      format.json { head :no_content }
    end
  end
  
  #-----------------custom stuff
  def correct_user
    @recipe = current_user.recipes.find_by(id: params[:id])
    redirect_to recipes_path, notice: "Not authorized!" if @recipe.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find_by_id(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def recipe_params
      params.require(:recipe).permit(:name, :user_id, :global, :status)
    end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<%= form_with(model: recipe) do |form| %>
  <% if recipe.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
        <% recipe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="modal-body">
    <div>
      <%= form.label :name, style: "display: block" %>
      <%= form.text_field :name %>
    </div>

    <div>
      <%= form.number_field :user_id, id: :recipe_user_id, value: current_user.id, type: :hidden %>
    </div>
    <div>
      <%= form.label :status, style: "display: block" %>
      <%= form.select :status, [["In Progress","IP"],["Published","PB"]]%>
    </div>
    <% if current_user.admin == "T" %>
      <div>
        <%= form.label :global, style: "display: block" %>
        <%= form.select :global, [["True","T"],["False","F"]] %>
      </div>
    <% end %>
  </div>
  <div class="modal-footer">
    <%= form.submit class: "btn btn-secondary" %>
  </div>
<% end %>
  

app/views/recipes/_recipe.html.erb
<li id="<%= dom_id recipe %>" class="<% if recipe.status == "IP" %> <%= recipe.status %>  <% else %> themeColor <% end %> list-group-item list-group-item-action list-group-item-secondary">
    <%= link_to recipe.name, recipe %>
</li>

app/views/recipes/_recipeTitle.html.erb
<h2 id="recipeTitle"><%= @recipe.name %></h2>

app/views/recipes/edit.html.erb
<%= turbo_frame_tag :zFormModal do %>
  <div data-controller="z-form-modal" data-action="turbo:submit-end->z-form-modal#submitEnd">
    <div class="modal-header themeColor">
      <h5 class="modal-title" id="staticBackdropLabel">Editing recipe</h5>
      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
    </div>
    <%= render "form", recipe: @recipe %>
  </div>
<% end %>

app/views/recipes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Recipes</h1>
<p>
  <%= link_to "New Recipe", new_recipe_path, data:{turbo_frame: "zFormModal", controller: "z-form-modal", action: "z-form-modal#showModal"} %>
</p>
<ul id="recipes" class="list-group">
  <% @recipes.each do |recipe| %>
    <%= render recipe %>
  <% end %>
</ul>

app/views/recipes/new.html.erb
<%= turbo_frame_tag :zFormModal do %>
  <div data-controller="z-form-modal" data-action="turbo:submit-end->z-form-modal#submitEnd">
    <div class="modal-header themeColor">
      <h5 class="modal-title" id="staticBackdropLabel">New recipe</h5>
      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
    </div>
    <%= render "form", recipe: @recipe %>
  </div>
<% end %>

app/views/recipes/show.html.erb
<p style="color: green"><%= notice %></p>
<div class="bucket">
  <div class="build-recipe">
    <ul class="recipe-utility-list">
      <li><h2 id="recipeTitle"><%= @recipe.name %></h2></li>
      <li><div>
      <%= link_to edit_recipe_path(@recipe), data:{turbo_frame: "zFormModal", controller: "z-form-modal", action: "z-form-modal#showModal"} do %>
        <i class="bi bi-pencil"></i>
      <% end %>
      <%= link_to @recipe, data: {turbo_method: :delete, turbo_confirm: "For real?" } do %>
        <i class="bi bi-trash3"></i>
      <% end %>
      </div></li>      
    </ul>
  </div>
  <div class="recipe_ingredients">
    <ul class="recipe-ingredients-list" id="recipe-ingredients-container">
      <li>
        <%= link_to "add ingredient to recipe", new_recipe_recipe_ingredient_path(@recipe), data:{turbo_frame: "zFormModal", controller: "z-form-modal", action: "z-form-modal#showModal"}, class: "btn btn-secondary"%>
      </li>
      <% if @recipe_ingredients.each do |recipe_ingredient| %>
        <%= render recipe_ingredient %>
      <% end.empty? %>
        <li class="noItems">No ingredients</li>
      <% end %>
  </div>
  <div class="recipe_steps">
    <ul class="recipe-steps-list" id="recipe-steps-container">
      <li><%= link_to "add step to recipe", new_recipe_recipe_step_path(@recipe), data:{turbo_frame: "zFormModal", controller: "z-form-modal", action: "z-form-modal#showModal"},class: "btn btn-secondary" %></li>
      <% if @recipe_steps.each do |recipe_step| %>
        <%= render recipe_step %>
      <% end.empty? %>
        <li class="noItems">No steps</li>
      <% end %>
    </ul>
  </div>
</div>