config/routes.rb
Rails.application.routes.draw do
  resources :meal_preps
  root "home#index"
  
  resources :recipes do 
    resources :recipe_steps
    resources :recipe_ingredients
  end
  resources :locations
  get 'users/index'
  resources :ingredients
  resources :states
  resources :units
  #devise_for :users
  devise_for :users, controllers: { registrations: "registrations" }
  #get 'home/index'
  #get 'create_update/index'
  get "home/about"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
  get "recipe_ingredients/test"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
    belongs_to :user
    belongs_to :state
    belongs_to :location
    has_many :recipe_ingredients
end

app/models/location.rb
class Location < ApplicationRecord
    belongs_to :user
    has_many :ingredients
end

app/models/meal_prep.rb
class MealPrep < ApplicationRecord
  belongs_to :user
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord
    belongs_to :user
    has_many :recipe_steps, dependent: :destroy
    has_many :recipe_ingredients, dependent: :destroy
    has_many :ingredients, :through => :recipe_ingredients
    has_many :units, :through => :recipe_ingredients
    has_many :meal_preps

    validates :name, presence: true
end

app/models/recipe_ingredient.rb
class RecipeIngredient < ApplicationRecord
    belongs_to :recipe
    belongs_to :ingredient
    belongs_to :unit
    belongs_to :user
end

app/models/recipe_step.rb
class RecipeStep < ApplicationRecord
    belongs_to :recipe
    belongs_to :user
end

app/models/state.rb
class State < ApplicationRecord
    belongs_to :user
    has_many :ingredients
end

app/models/unit.rb
class Unit < ApplicationRecord
    belongs_to :user
    has_many :recipe_ingredients
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :units
  has_many :states
  has_many :ingredients
  has_many :locations
  has_many :recipes
  has_many :recipe_ingredients
  has_many :recipe_steps
  has_many :meal_preps
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if user_signed_in?
      if current_user.admin == "T"
        @recipes = Recipe.all.order(name: :asc)
      else
        #@recipes = current_user.recipes.or(Recipe.where(global: "T", status: "PB")).order(name: :asc)
        @recipes = Recipe.where("user_id=? or (global=? and status=?)",current_user.id,"T","PB").order(name: :asc)
      end
    else
        @recipes = Recipe.where(global: "T", status: "PB").order(name: :asc)
    end
  end
  
  def about
  end
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  before_action :set_unit, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  #Only allow editing, updating and destroying of units associated with the current user
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /units or /units.json
  def index
    @units = Unit.where("user_id=? or global=?",current_user.id,"T").order(name: :asc)
  end

  # GET /units/1 or /units/1.json
  def show
  end

  # GET /units/new
  def new
    @unit = Unit.new
  end

  # GET /units/1/edit
  def edit
  end

  # POST /units or /units.json
  def create
    @unit = Unit.new(unit_params)

    respond_to do |format|
      if @unit.save
        format.html { redirect_to unit_url(@unit), notice: "Unit was successfully created." }
        format.json { render :show, status: :created, location: @unit }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /units/1 or /units/1.json
  def update
    respond_to do |format|
      if @unit.update(unit_params)
        format.html { redirect_to unit_url(@unit), notice: "Unit was successfully updated." }
        format.json { render :show, status: :ok, location: @unit }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /units/1 or /units/1.json
  def destroy
    @unit.destroy

    respond_to do |format|
      format.html { redirect_to units_url, notice: "Unit was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @unit = current_user.units.find_by(id: params[:id])
    redirect_to units_path, notice: "Not authorized!" if @unit.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_unit
      @unit = Unit.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def unit_params
      params.require(:unit).permit(:name, :user_id, :global)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/meal_preps_helper.rb
module MealPrepsHelper
end

app/helpers/recipe_steps_helper.rb
module RecipeStepsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light themeColor">
  <div class="container-fluid">
    <%= link_to "Recipes", root_path, class:"navbar-brand" %>
    
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Locations", locations_path, data:{turbo_frame: "zFormModal", controller: "z-form-modal", action: "z-form-modal#showModal"}, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Meal Prep", meal_preps_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "States", states_path, data:{turbo_frame: "zFormModal", controller: "z-form-modal", action: "z-form-modal#showModal"}, class: "nav-link" %>
          </li>          
          <li class="nav-item">
            <%= link_to "Units", units_path, data:{turbo_frame: "zFormModal", controller: "z-form-modal", action: "z-form-modal#showModal"}, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Ingredients", ingredients_path, data:{turbo_frame: "zFormModal", controller: "z-form-modal", action: "z-form-modal#showModal"}, class: "nav-link" %>
            <%#= link_to "Ingredients", ingredients_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Recipe Maintenance", recipes_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign Out", destroy_user_session_path, data: {turbo_method: :delete }, class:"nav-link" %>
          </li>
          <li class="nav-item row">
            <%= link_to edit_user_registration_path, class:"nav-link col" do %><i class="bi bi-gear-fill"></i><% end %>
          </li>
        <% else %>
            <li class="nav-item">
              <%= link_to "Sign up", new_user_registration_path, class:"nav-link"%>
            </li>
            <li class="nav-item">
              <%= link_to "Sign in", new_user_session_path, class:"nav-link"  %>
            </li>
        <% end %>

      </ul>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>Recipes...</h1>
<p>I am not a cook, but I do need to eat. When I do want to cook something that is more than just fullfilling my caloric requirements for the day, I don't want to read a bunch of crap while sifting through a page for the actual recipe.</p>
<p>I don't care that your child has a peanut allergy. I really don't. I empathize, but the recipe you put on the internet is what I'm interested in.</p>
<p>I don't care that you first made the recipe when you proposed to your wife.<p>
<p>Here are other tings I don't care about</p>
<ul>
    <li>The memories you have while cooking this</li>
    <li>Pictures of the meal</li>
    <li>That your favorite thing in life is time around the table</li>
    <li>That this is your favorite recipe</li>
    <li>Something that happened a few weeks ago on insta</li>
</ul>
<p>Pretty much, I don't care about anything on the page that doesn't have to do with the actual recipe. So, I decided to make a webpage that would give me a recipe without all of the other <strike>garbage</strike> stuff most recipe pages put on them <strike>to make the page longer so more ads can be displayed</strike>.

app/views/home/index.html.erb
<%= javascript_include_tag "scripts" %>
<% if @recipes.empty? %>
    <div class="recipesWrapper">
        <p>NO RECIPES!!!1</p>
    </div>
<% else %>
    <input class="searcher" id="filterRecipes" onkeyup="filterRecipes(this)" type="text" placeholder="Search for ingredient...">
    <div class="recipesWrapper">        
    <% @recipes.each do |recipe| %>
        <div data-controller="recipe" data-controller="recipe" data-action="click->recipe#show" id="recipe_<%= recipe.id %>" class="recipe <% if recipe.status == "IP"%>IP<% end %>" data-name="<%= recipe.name%>" 
        data-steps="<% recipe.recipe_steps.each do |recipe_step| %><p><%= recipe_step.step_number %>. <%= recipe_step.step_text %></p><% end %>" data-ingredients="<% recipe.recipe_ingredients.each do |ri|%><p><%= ri.amount %> <%= ri.unit.name %> <%= ri.ingredient.name %> <% if ri.prep_instructions == "" %><% else %>(<%= ri.prep_instructions %>)<% end %></p><% end %>"><%= recipe.name%><% if recipe.global == "T"%><i class="bi bi-globe"></i><%end%></div>
    <% end %>
    </div>
<% end %>



        
<div class="overlay noShow">    
    <div class="tModal" id="myModal">    
        <div class="try">
            <div id="recNam"></div>
            <div id="oneLT">
                <div class="close" id="closer" data-controller="recipe" data-action="click->recipe#modalClose">&times;</div>
            </div>
        </div>
        <div class="modal-guts">
            <div id="recIngs"></div>
            <div id="recSteps"></div>
        </div>
    </div>
</div>