config/routes.rb
Rails.application.routes.draw do
  resources :meal_preps
  root "home#index"
  
  resources :recipes do 
    resources :recipe_steps
    resources :recipe_ingredients
  end
  resources :locations
  get 'users/index'
  resources :ingredients
  resources :states
  resources :units
  #devise_for :users
  devise_for :users, controllers: { registrations: "registrations" }
  #get 'home/index'
  #get 'create_update/index'
  get "home/about"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
  get "recipe_ingredients/test"
end

app/models/meal_prep.rb
class MealPrep < ApplicationRecord
  belongs_to :user
  belongs_to :recipe
end

app/controllers/meal_preps_controller.rb
class MealPrepsController < ApplicationController
  before_action :set_meal_prep, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update, :destroy]
  # GET /meal_preps or /meal_preps.json
  def index
    start_date = params.fetch(:start_date, Date.today).to_date
    #used for the calendar
    @meal_preps = current_user.meal_preps.where(start_time: start_date.beginning_of_week...start_date.end_of_week).includes(:recipe).order("meal_preps.start_time")
    #used to get the total ingredients
    @testValue = current_user.meal_preps.where(start_time: start_date.beginning_of_week...start_date.end_of_week).joins(recipe: [ recipe_ingredients: [ :ingredient, :unit ] ] ).group("ingredients.name, units.name").select("sum(recipe_ingredients.amount) as tAmount, units.name as unit, ingredients.name as ingredient").order("ingredients.name, units.name")
  end

  # GET /meal_preps/1 or /meal_preps/1.json
  def show
  end

  # GET /meal_preps/new
  def new
    #@meal_prep = MealPrep.new
    @meal_prep = current_user.meal_preps.build
    @recipes = Recipe.where("user_id=? or global=?", current_user.id, "T").order(name: :asc)
  end

  # GET /meal_preps/1/edit
  def edit
    @recipes = Recipe.where("user_id=? or global=?", current_user.id, "T").order(name: :asc)
  end

  # POST /meal_preps or /meal_preps.json
  def create
    #@meal_prep = MealPrep.new(meal_prep_params)
    #@meal_prep = current_user.meal_preps.build(meal_prep_params)
    @meal_prep = current_user.meal_preps.build(meal_prep_params)

    respond_to do |format|
      if @meal_prep.save
#need to figure out actions after save of meal_prep
        format.html { redirect_to meal_preps_url, status: :see_other, notice: "Meal added!" }
        #format.html { redirect_to meal_prep_url(@meal_prep), notice: "Meal prep was successfully created." }
        format.json { render :show, status: :created, location: @meal_prep }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @meal_prep.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meal_preps/1 or /meal_preps/1.json
  def update
    respond_to do |format|
      if @meal_prep.update(meal_prep_params)
        format.html { redirect_to meal_prep_url(@meal_prep), notice: "Meal prep was successfully updated." }
        format.json { render :show, status: :ok, location: @meal_prep }
      else
        format.html { render :edit, status: :unprocessable_entity }
       format.json { render json: @meal_prep.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meal_preps/1 or /meal_preps/1.json
  def destroy
    @meal_prep.destroy

    respond_to do |format|
      format.html { redirect_to meal_preps_url, notice: "Meal prep was successfully destroyed." }
      format.json { head :no_content }
    end
  end
  
  #-----------------custom stuff
  def correct_user
    @meal_prep = current_user.meal_preps.find_by(id: params[:id])
    redirect_to meal_prep_path, notice: "Not authorized!" if @meal_prep.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meal_prep
      @meal_prep = MealPrep.find_by_id(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def meal_prep_params
      params.require(:meal_prep).permit(:users_id, :meal_date, :meal_type, :recipe_id, :start_time, :end_time)
    end
end

app/helpers/meal_preps_helper.rb
module MealPrepsHelper
end

app/views/meal_preps/_form.html.erb
<%= form_with(model: meal_prep) do |form| %>
  <% if meal_prep.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(meal_prep.errors.count, "error") %> prohibited this meal_prep from being saved:</h2>

      <ul>
        <% meal_prep.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="modal-body">
    <div>
      <%= form.number_field :user_id, id: :recipe_user_id, value: current_user.id, type: :hidden %>
    </div>
    <div>
      <%= form.label :recipe_id, style: "display: block" %>
      <%= form.select :recipe_id, @recipes.map { |r| [r.name, r.id] }, selected: params[:recipe_id]%>
    </div>
    <div>
      <%= form.label :start_time, style: "display: block" %>
      <%= form.datetime_local_field :start_time, value: params[:start_time] %>
    </div>
  </div>
  <div class="modal-footer">
    <%= form.submit class: "btn btn-secondary" %>
  </div>
<% end %>

app/views/meal_preps/_meal_prep.html.erb
<div id="<%= dom_id meal_prep %>" class="row">
  <%= meal_prep.recipe.name %>
  <div class="col">
      <%= link_to meal_prep, data: {turbo_method: :delete, turbo_confirm: "Delete meal?"} do %><i class="bi bi-trash3"></i><% end %>
    </div>
</div>

app/views/meal_preps/edit.html.erb
<%= turbo_frame_tag :zFormModal do %>
  <div data-controller="z-form-modal" data-action="turbo:submit-end->z-form-modal#submitEnd">
    <div class="modal-header themeColor">
      <h5 class="modal-title" id="staticBackdropLabel">Editing meal</h5>
      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
    </div>
    <%= render "form", meal_prep: @meal_prep %>
  </div>
<% end %>

app/views/meal_preps/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Meal preps</h1>
<div class="row">
  <div class="col">
    <%= week_calendar(events: @meal_preps) do |date, meal_preps| %>
      <div>
        <div class="row">
          <h6 class="col"><%= date.strftime("%b %d (%A)") %></h6><%= link_to new_meal_prep_path(start_time: date.strftime("%Y-%m-%dT%H:%M")), data:{turbo_frame: "zFormModal", controller: "z-form-modal", action: "z-form-modal#showModal"},class:"col-1" do %><i class="bi bi-plus-circle"></i><% end %>
        </div>
      </div>
      <% meal_preps.each do |meal_prep| %>
        <%= render meal_prep %>
      <% end %>
    <% end %>
  </div>
  <div class="col">
    <ul class="list-group">
      <% @testValue.each do |t| %>
        <li class="list-group-item"><%= t.tAmount.to_s + " " + t.unit + " " + t.ingredient %></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/meal_preps/new.html.erb
<%= turbo_frame_tag :zFormModal do %>
  <div data-controller="z-form-modal" data-action="turbo:submit-end->z-form-modal#submitEnd">
    <div class="modal-header themeColor">
      <h5 class="modal-title" id="staticBackdropLabel">New meal prep</h5>
      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
    </div>
    <%= render "form", meal_prep: @meal_prep %>
  </div>
<% end %>

app/views/meal_preps/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @meal_prep %>

<div>
  <%= link_to "Edit this meal prep", edit_meal_prep_path(@meal_prep) %> |
  <%= link_to "Back to meal preps", meal_preps_path %>

  <%= button_to "Destroy this meal prep", @meal_prep, method: :delete %>
</div>